export interface Wilaya {
  code: string;
  nom: string;
}

export const WILAYAS_ALGERIE: Wilaya[] = [
  { code: "01", nom: "Adrar" },
  { code: "02", nom: "Chlef" },
  { code: "03", nom: "Laghouat" },
  { code: "04", nom: "Oum El Bouaghi" },
  { code: "05", nom: "Batna" },
  { code: "06", nom: "Béjaïa" },
  { code: "07", nom: "Biskra" },
  { code: "08", nom: "Béchar" },
  { code: "09", nom: "Blida" },
  { code: "10", nom: "Bouira" },
  { code: "11", nom: "Tamanrasset" },
  { code: "12", nom: "Tébessa" },
  { code: "13", nom: "Tlemcen" },
  { code: "14", nom: "Tiaret" },
  { code: "15", nom: "Tizi Ouzou" },
  { code: "16", nom: "Alger" },
  { code: "17", nom: "Djelfa" },
  { code: "18", nom: "Jijel" },
  { code: "19", nom: "Sétif" },
  { code: "20", nom: "Saïda" },
  { code: "21", nom: "Skikda" },
  { code: "22", nom: "Sidi Bel Abbès" },
  { code: "23", nom: "Annaba" },
  { code: "24", nom: "Guelma" },
  { code: "25", nom: "Constantine" },
  { code: "26", nom: "Médéa" },
  { code: "27", nom: "Mostaganem" },
  { code: "28", nom: "M'Sila" },
  { code: "29", nom: "Mascara" },
  { code: "30", nom: "Ouargla" },
  { code: "31", nom: "Oran" },
  { code: "32", nom: "El Bayadh" },
  { code: "33", nom: "Illizi" },
  { code: "34", nom: "Bordj Bou Arreridj" },
  { code: "35", nom: "Boumerdès" },
  { code: "36", nom: "El Tarf" },
  { code: "37", nom: "Tindouf" },
  { code: "38", nom: "Tissemsilt" },
  { code: "39", nom: "El Oued" },
  { code: "40", nom: "Khenchela" },
  { code: "41", nom: "Souk Ahras" },
  { code: "42", nom: "Tipaza" },
  { code: "43", nom: "Mila" },
  { code: "44", nom: "Aïn Defla" },
  { code: "45", nom: "Aïn Témouchent" },
  { code: "46", nom: "Ghardaïa" },
  { code: "47", nom: "Relizane" },
  { code: "48", nom: "Timimoun" },
  { code: "49", nom: "Bordj Badji Mokhtar" },
  { code: "50", nom: "Ouled Djellal" },
  { code: "51", nom: "Béni Abbès" },
  { code: "52", nom: "In Salah" },
  { code: "53", nom: "In Guezzam" },
  { code: "54", nom: "Touggourt" },
  { code: "55", nom: "Djanet" },
  { code: "56", nom: "El M'Ghair" },
  { code: "57", nom: "El Meniaa" },
  { code: "58", nom: "Béni Ounif" },
];
